### ISSUE TITLE
[MWAR-158] Overlaying breaks configuration of webXml with a fatal error

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-war-plugin#338]
**[Michael Heß](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=m_hess)** opened **[MWAR-158](https://issues.apache.org/jira/browse/MWAR-158?redirect=false)** and commented

When using overlays, it is no longer possible to use the webXml configuration value. The following exception is thrown:

[INFO] [war:war]
[INFO] Packaging webapp
[INFO] Assembling webapp[webXmlBug] in [/home/mhe/workspace_spielwiese/webXmlBug/target/webXmlBug]
[INFO] Processing war project
OverlayPackagingTask performPackaging overlay.getTargetPath() null[INFO] Processing overlay[ id de.ordix.webXmlBug:overlay]
[INFO] Unpacking overlay[ id de.ordix.webXmlBug:overlay]
[INFO] Expanding: /home/mhe/.m2/repository/de/ordix/webXmlBug/overlay/1.0-SNAPSHOT/overlay-1.0-SNAPSHOT.war into /home/mhe/workspace_spielwiese/webXmlBug/target/war/work/de.ordix.webXmlBug/overlay
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Should not happen, path[WEB-INF/web.xml] is flagged as being registered but was not found.
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.IllegalStateException: Should not happen, path[WEB-INF/web.xml] is flagged as being registered but was not found.
at org.apache.maven.plugin.war.util.WebappStructure.getOwner(WebappStructure.java:157)
at org.apache.maven.plugin.war.util.WebappStructure.registerFile(WebappStructure.java:105)
at org.apache.maven.plugin.war.packaging.AbstractWarPackagingTask.copyFile(AbstractWarPackagingTask.java:140)
[...]

I have attached a testcase, which reproduces the problem. Just build overlay and webXmlBug with "mvn clean install".

(I know the testcase is synthetic. If you want a "real world" scenario, just replace the resources-copy step with e.g. jsp-precompiling.)

---

**Affects:** 2.1-alpha-1

**Attachments:**
- [webXmlBug.tar.gz](https://issues.apache.org/jira/secure/attachment/12720482/webXmlBug.tar.gz) (_1.37 kB_)

6 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Michael Heß](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=m_hess)** commented

Why is this bug supposed to affect 2.1-alpha-1 ?
As I posted, it affects the current version 2.0.9.

`@Stephane`: Why did you demote it from blocker to critical? It clearly breaks the build. IMHO it therefore is a blocker. Could you please elaborate on this change?

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

This is the plugin version, not the maven version (i.e. versions specified here are the war plugin version since we are in the war plugin jira project).

It make no sense to have blocking issues here since nobody will have a look to it **right now** (there is no SLA, this is open source and community based). I agree it is cirticial and must be fixed for the next release though.

**Comment by jira-importer** [comment]
**[David Bernard](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=davidbernard)** commented

The following seems to work as a workaround.  
The "overlay" is laid down first excluding web.xml and the web app is then overlayed on top.

          <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <webXml>${project.build.directory}/jspweb.xml</webXml>
                    <warName>${project.build.finalName}</warName>
                    <overlays>
                        <overlay>
                            <groupId>com.xxxx.core</groupId>
                            <artifactId>xxx-user</artifactId>
                            <type>war</type>
                            <excludes>
                                <exclude>WEB/web.xml</exclude>
                            </excludes>
                        </overlay>
                        <overlay>
    
                        </overlay>
                    </overlays>
                </configuration>
            </plugin>

**Comment by jira-importer** [comment]
**[Simone Pierazzini](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=makeroo)** commented

I think that the exception occurs because WarProjectPackagingTask registers the path in the FullStructure only.
If one modifies the class as shown in the following the build doesn't fail anymore.

I don't know if it's correct to use WarProjectPackagingTask.id to identify the war project as the owner.

Index: src/main/java/org/apache/maven/plugin/war/packaging/WarProjectPackagingTask.java

---

--- src/main/java/org/apache/maven/plugin/war/packaging/WarProjectPackagingTask.java    (revisione 768245)
+++ src/main/java/org/apache/maven/plugin/war/packaging/WarProjectPackagingTask.java    (copia locale)
@@ -230,6 +230,7 @@
}

    context.getWebappStructure().getFullStructure().add( WEB_INF_PATH + "/web.xml" );

+ 

          context.getWebappStructure().getStructure(id).add( WEB_INF_PATH + "/web.xml" );
      }
      else
      {

@@ -241,6 +242,7 @@
context.getMavenFileFilter().copyFile( defaultWebXml, new File( webinfDir, "web.xml" ), true,
context.getFilterWrappers(), getEncoding( defaultWebXml ) );
context.getWebappStructure().getFullStructure().add( WEB_INF_PATH + "/web.xml" );
+

            context.getWebappStructure().getStructure(id).add( WEB_INF_PATH + "/web.xml" );
        }
    }

@@ -259,6 +261,7 @@
"META-INF/" + xmlFileName, true );
}
context.getWebappStructure().getFullStructure().add( META_INF_PATH + "/" + xmlFileName );
+

            context.getWebappStructure().getStructure(id).add( META_INF_PATH + "/" + xmlFileName );
        }
    }
    catch ( IOException e )

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Simone is right. I have extended WebappStructure to allow to "force" register a path with a new owner if necessary.
