### ISSUE TITLE
[MWAR-184]  FATAL ERROR -  XPP3 pull parser library not present. Specify another driver.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-war-plugin#358]
**[Matthew Corby-Eaglen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=matt.corby)** opened **[MWAR-184](https://issues.apache.org/jira/browse/MWAR-184?redirect=false)** and commented

building my project from a master build pom

```
These will use the artifact files already in the core ClassRealm instead, to allow them to be included in PluginDescriptor.getArtifacts().


[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-war-plugin:2.1-alpha-1:war' -->
[DEBUG]   (s) archiveClasses = false
[DEBUG]   (s) cacheFile = /data/cruisecontrol/projects/MavenBuildModule-2-2-36/VcCasinoCapi/target/war/work/webapp-cache.xml
[DEBUG]   (s) classesDirectory = /data/cruisecontrol/projects/MavenBuildModule-2-2-36/VcCasinoCapi/target/classes
[DEBUG]   (s) filters = []
[DEBUG]   (f) outputDirectory = /data/cruisecontrol/projects/MavenBuildModule-2-2-36/VcCasinoCapi/target
[DEBUG]   (f) primaryArtifact = true
[DEBUG]   (s) project = MavenProject: com.vcint:VcCasinoCapi:2.2.36-SNAPSHOT @ /data/cruisecontrol/projects/MavenBuildModule-2-2-36/VcCasinoCapi/pom.xml
[DEBUG]   (s) useCache = true
[DEBUG]   (f) warName = VcCasinoCapi
[DEBUG]   (s) warSourceDirectory = /data/cruisecontrol/projects/MavenBuildModule-2-2-36/VcCasinoCapi/src/main/webapp
[DEBUG]   (s) webappDirectory = /data/cruisecontrol/projects/MavenBuildModule-2-2-36/VcCasinoCapi/target/VcCasinoCapi
[DEBUG]   (s) workDirectory = /data/cruisecontrol/projects/MavenBuildModule-2-2-36/VcCasinoCapi/target/war/work
[DEBUG] -- end configuration --
[INFO] [war:war]
[INFO] Packaging webapp
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] XPP3 pull parser library not present. Specify another driver. For example: new XStream(new DomDriver())
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
java.lang.IllegalArgumentException: XPP3 pull parser library not present. Specify another driver. For example: new XStream(new DomDriver())
        at com.thoughtworks.xstream.io.xml.XppDriver.loadLibrary(XppDriver.java:42)
        at com.thoughtworks.xstream.io.xml.XppDriver.createReader(XppDriver.java:29)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:781)
        at org.apache.maven.plugin.war.util.WebappStructureSerializer.fromXml(WebappStructureSerializer.java:48)
        at org.apache.maven.plugin.war.AbstractWarMojo.buildWebapp(AbstractWarMojo.java:346)
        at org.apache.maven.plugin.war.AbstractWarMojo.buildExplodedWebapp(AbstractWarMojo.java:317)
        at org.apache.maven.plugin.war.WarMojo.performPackaging(WarMojo.java:166)
        at org.apache.maven.plugin.war.WarMojo.execute(WarMojo.java:130)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:324)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16 seconds
[INFO] Finished at: Tue Feb 17 14:23:49 CET 2009
[INFO] Final Memory: 11M/21M
[INFO] ------------------------------------------------------------------------
```

---

**Affects:** 2.1-alpha-1

2 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Joerg Schaible](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joehni)** commented

XStream's XppDriver used by default is unfortunately testing the availability of the Xpp3 parser using Class.forName(...) which can fail with special classloader setups. This might be the case here, I see Matthiew is using CruiseControl. XSTR-542 already addresses this. I try to push a new XStream release this weekend to get included into the upcoming war plugin version.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

I upgraded XStream to version 1.3.1, as recommended by Jörn Schaible. Hopefully it solves this issue. A new 2.1-beta-1-SNAPSHOT has been deployed.

**Comment by jira-importer** [comment]
**[Joerg Schaible](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joehni)** commented

Actually, this particular problem is not yet fixed in XStream :(

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Thanks for clarifying that Jörg.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

The driver to use is now explicitly provided.
