### ISSUE TITLE
[MWAR-187] regression running war packaging with maven 2.1

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-war-plugin#360]
**[nicolas de loof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ndeloof)** opened **[MWAR-187](https://issues.apache.org/jira/browse/MWAR-187?redirect=false)** and commented

Using plugin version 2.1-beta-1, my webapp can't get packaged.
It can be fixed by downgrading the plugin to 2.0.2

```
 
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-war-plugin:2.1-beta-1:w
ar' -->
[DEBUG]   (s) archiveClasses = false
[DEBUG]   (s) attachClasses = false
[DEBUG]   (s) cacheFile = D:\...\target\war\work\webapp-cache.xml
[DEBUG]   (s) classesClassifier = classes
[DEBUG]   (s) classesDirectory = D:\...\target\classes
[DEBUG]   (f) escapedBackslashesInFilePath = false
[DEBUG]   (s) failOnMissingWebXml = true
[DEBUG]   (f) filteringDeploymentDescriptors = false
[DEBUG]   (s) outputDirectory = D:\...\target
[DEBUG]   (s) primaryArtifact = true
[DEBUG]   (s) project = MavenProject: com.sfr.bios.pdc:bios-pdc-webservices:1.0.
0-SNAPSHOT @ D:\...\pom.xml

[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@10f0a0
[DEBUG]   (s) useCache = true
[DEBUG]   (s) warName = bios-pdc
[DEBUG]   (s) warSourceDirectory = D:\...\src\main\webapp
[DEBUG]   (s) webappDirectory = D:\...\target\bios-pdc-webservices-1.0.0-SNAPSHOT
[DEBUG]   (s) workDirectory = D:\...\target\war\work
[DEBUG] -- end configuration --
[INFO] [war:war]
[INFO] Packaging webapp
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] modelEncoding : modelEncoding : modelEncoding : modelEncoding
---- Debugging information ----
message             : modelEncoding : modelEncoding
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassExceptio
n
cause-message       : modelEncoding : modelEncoding
class               : org.apache.maven.plugin.war.util.WebappStructure
required-type       : org.apache.maven.model.Dependency
path                : /webapp-structure/dependenciesInfo/org.apache.maven.plugin
.war.util.DependencyInfo/dependency/modelEncoding
line number         : 156
-------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Trace
com.thoughtworks.xstream.converters.ConversionException: modelEncoding : modelEn
coding : modelEncoding : modelEncoding
---- Debugging information ----
message             : modelEncoding : modelEncoding
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassExceptio
n
cause-message       : modelEncoding : modelEncoding
class               : org.apache.maven.plugin.war.util.WebappStructure
required-type       : org.apache.maven.model.Dependency
path                : /webapp-structure/dependenciesInfo/org.apache.maven.plugin
.war.util.DependencyInfo/dependency/modelEncoding
line number         : 156
-------------------------------
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshall
er.java:89)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(A
bstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:76)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.unmarshallField(AbstractReflectionConverter.java:246)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.doUnmarshal(AbstractReflectionConverter.java:218)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.unmarshal(AbstractReflectionConverter.java:162)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshall
er.java:82)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(A
bstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:76)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:60)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionCon
verter.readItem(AbstractCollectionConverter.java:71)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.p
opulateCollection(CollectionConverter.java:68)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.u
nmarshal(CollectionConverter.java:61)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshall
er.java:82)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(A
bstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:76)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.unmarshallField(AbstractReflectionConverter.java:246)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.doUnmarshal(AbstractReflectionConverter.java:218)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.unmarshal(AbstractReflectionConverter.java:162)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshall
er.java:82)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(A
bstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:76)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:60)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller
.java:137)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarsh
al(AbstractTreeMarshallingStrategy.java:33)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:923)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:909)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:853)
        at org.apache.maven.plugin.war.util.WebappStructureSerializer.fromXml(We
bappStructureSerializer.java:73)
        at org.apache.maven.plugin.war.AbstractWarMojo.buildWebapp(AbstractWarMo
jo.java:423)
        at org.apache.maven.plugin.war.AbstractWarMojo.buildExplodedWebapp(Abstr
actWarMojo.java:394)
        at org.apache.maven.plugin.war.WarMojo.performPackaging(WarMojo.java:195
)
        at org.apache.maven.plugin.war.WarMojo.execute(WarMojo.java:157)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:483)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:678)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:540)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:519)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:371)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:332)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:181)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: modelEnc
oding : modelEncoding
        at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper
.java:68)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicP
roxyMapper.java:71)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(Packa
geAliasingMapper.java:88)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAl
iasingMapper.java:86)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.jav
a:96)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper
.java:52)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.determineType(AbstractReflectionConverter.java:347)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.doUnmarshal(AbstractReflectionConverter.java:208)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.unmarshal(AbstractReflectionConverter.java:162)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshall
er.java:82)
        ... 50 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24 seconds
[INFO] Finished at: Wed Mar 25 08:33:07 CET 2009
[INFO] Final Memory: 30M/71M
[INFO] ----------------------
```

---

**Affects:** 2.1-beta-1

**Attachments:**
- [MWAR-187-bad_webapp_cache.zip](https://issues.apache.org/jira/secure/attachment/12720476/MWAR-187-bad_webapp_cache.zip) (_5.87 kB_)

**Issue Links:**
- [MWAR-191](https://issues.apache.org/jira/browse/MWAR-191) CannotResolveClassException when switching to tomcat deployment with context.xml
 (_**"is duplicated by"**_)
- [MWAR-209](https://issues.apache.org/jira/browse/MWAR-209) modelEncoding com.thoughtworks.xstream.mapper.CannotResolveClassException
 (_**"is duplicated by"**_)
- [MWAR-231](https://issues.apache.org/jira/browse/MWAR-231) Disable webapp cache by default

16 votes, 19 watchers

**Comment by jira-importer** [comment]
**[Hendy Irawan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ceefour)** commented

Downgrading to war-plugin 2.0.2 didn't solve the problem for me, it gave me yet another problem by including bad dependencies in WEB-INF/lib. (i.e., some "provided" dependencies such as el-api and jsp-api were included).

I downgraded to war-plugin 2.1-alpha-2 which solved the problem, the most recent version that worked for my case.

**Comment by jira-importer** [comment]
**[Pablo Fernandez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pablo)** commented

Please have a look at the project `MWAR-187-bad_webapp_cache.zip`.
I'm not really sure how this badly formatted `webapp-cache.xml` file (i.e. containing a `modelEncoding` node) ended up in my target folder, but this was the cause of my problem.

Here is how to reproduce the problem with Maven 2.1.0:
* Run `mvn install` and the exception described above will occur.
* Run `mvn clean install` and the packaging will work fine (because the target folder containing the badly formatted file will be deleted)

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Pablo, This is not a forum, this is an issue tracker. Your problem as NOTHING to do with this issue. Please create an appropriate issue if none exists for your problem.

**Comment by jira-importer** [comment]
**[Pablo Fernandez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pablo)** commented

I know what JIRA is, thanks.
My aim was just to provide a test case for this issue (as good JIRA users usually do), not to ask for help as a newbie would do in a forum.

Are you sure that "NOTHING" is the appropriate word?
Forcing the plugin version to 2.1-beta-1, the stack trace is EXACTLY the same as the one provided in the description (feel free to do a diff).

```
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-war-plugin:2.1-beta-1:w
ar' -->
[DEBUG]   (s) archiveClasses = false
[DEBUG]   (s) attachClasses = false
[DEBUG]   (s) cacheFile = D:\Work\Dev\Projects\MWAR-187-bad_webapp_cache\target\
war\work\webapp-cache.xml
[DEBUG]   (s) classesClassifier = classes
[DEBUG]   (s) classesDirectory = D:\Work\Dev\Projects\MWAR-187-bad_webapp_cache\
target\classes
[DEBUG]   (f) escapedBackslashesInFilePath = false
[DEBUG]   (s) failOnMissingWebXml = true
[DEBUG]   (f) filteringDeploymentDescriptors = false
[DEBUG]   (s) outputDirectory = D:\Work\Dev\Projects\MWAR-187-bad_webapp_cache\t
arget
[DEBUG]   (s) primaryArtifact = true
[DEBUG]   (s) project = MavenProject: blabla:blabla:0.1 @ D:\Work\Dev\Projects\M
WAR-187-bad_webapp_cache\pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@1d4d493
[DEBUG]   (s) useCache = true
[DEBUG]   (s) warName = blabla-0.1
[DEBUG]   (s) warSourceDirectory = D:\Work\Dev\Projects\MWAR-187-bad_webapp_cach
e\src\main\webapp
[DEBUG]   (s) webappDirectory = D:\Work\Dev\Projects\MWAR-187-bad_webapp_cache\t
arget\blabla-0.1
[DEBUG]   (s) workDirectory = D:\Work\Dev\Projects\MWAR-187-bad_webapp_cache\tar
get\war\work
[DEBUG] -- end configuration --
[INFO] [war:war]
[INFO] Packaging webapp
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] modelEncoding : modelEncoding : modelEncoding : modelEncoding
---- Debugging information ----
message             : modelEncoding : modelEncoding
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassExceptio
n
cause-message       : modelEncoding : modelEncoding
class               : org.apache.maven.plugin.war.util.WebappStructure
required-type       : org.apache.maven.model.Dependency
path                : /webapp-structure/dependenciesInfo/org.apache.maven.plugin
.war.util.DependencyInfo/dependency/modelEncoding
line number         : 23
-------------------------------
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
com.thoughtworks.xstream.converters.ConversionException: modelEncoding : modelEn
coding : modelEncoding : modelEncoding
---- Debugging information ----
message             : modelEncoding : modelEncoding
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassExceptio
n
cause-message       : modelEncoding : modelEncoding
class               : org.apache.maven.plugin.war.util.WebappStructure
required-type       : org.apache.maven.model.Dependency
path                : /webapp-structure/dependenciesInfo/org.apache.maven.plugin
.war.util.DependencyInfo/dependency/modelEncoding
line number         : 23
-------------------------------
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshall
er.java:89)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(A
bstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:76)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.unmarshallField(AbstractReflectionConverter.java:246)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.doUnmarshal(AbstractReflectionConverter.java:218)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.unmarshal(AbstractReflectionConverter.java:162)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshall
er.java:82)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(A
bstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:76)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:60)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionCon
verter.readItem(AbstractCollectionConverter.java:71)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.p
opulateCollection(CollectionConverter.java:68)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.u
nmarshal(CollectionConverter.java:61)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshall
er.java:82)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(A
bstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:76)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.unmarshallField(AbstractReflectionConverter.java:246)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.doUnmarshal(AbstractReflectionConverter.java:218)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.unmarshal(AbstractReflectionConverter.java:162)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshall
er.java:82)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(A
bstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:76)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnm
arshaller.java:60)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller
.java:137)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarsh
al(AbstractTreeMarshallingStrategy.java:33)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:923)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:909)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:853)
        at org.apache.maven.plugin.war.util.WebappStructureSerializer.fromXml(We
bappStructureSerializer.java:73)
        at org.apache.maven.plugin.war.AbstractWarMojo.buildWebapp(AbstractWarMo
jo.java:423)
        at org.apache.maven.plugin.war.AbstractWarMojo.buildExplodedWebapp(Abstr
actWarMojo.java:394)
        at org.apache.maven.plugin.war.WarMojo.performPackaging(WarMojo.java:195
)
        at org.apache.maven.plugin.war.WarMojo.execute(WarMojo.java:157)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:483)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:678)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:540)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:519)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:371)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:332)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:181)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: modelEnc
oding : modelEncoding
        at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper
.java:68)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicP
roxyMapper.java:71)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(Packa
geAliasingMapper.java:88)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAl
iasingMapper.java:86)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.jav
a:96)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper
.java:38)
        at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper
.java:52)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.determineType(AbstractReflectionConverter.java:347)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.doUnmarshal(AbstractReflectionConverter.java:208)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConv
erter.unmarshal(AbstractReflectionConverter.java:162)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshall
er.java:82)
        ... 50 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9 seconds
[INFO] Finished at: Thu Jun 04 11:13:49 CEST 2009
[INFO] Final Memory: 8M/17M
[INFO] ------------------------------------------------------------------------
```

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Rah, I read the wrong entry, sorry :)

**Comment by jira-importer** [comment]
**[Hendy Irawan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ceefour)** commented

Using 2.1-alpha-1 although "solved" the problem, it still occurs if the build is launched from a parent POM project, with the WAR project as a module.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

funny, I can't reproduce this on MacOS.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

One way to quickly work around this issue is to deactivate the cache.

```xml
<configuration>
  <useCache>false</useCache>
</configuration>
```

**Comment by jira-importer** [comment]
**[Pablo Fernandez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pablo)** commented

Cleaning or disabling cache are workarounds, but I think it would be a good thing anyway to catch this runtime exception.

I see two places where you could do this.
Either:
* In `WebappStructureSerializer.fromXml`, catch silently the `XStreamException` and return null.
  Then, `AbstractWarMojo.buildWebapp` will work properly, behaving as the "no cache" mode.

or:
* In `AbstractWarMojo.buildWebapp`, catch the `XStreamException` and branch to the "no cache" mode.
