### ISSUE TITLE
[MWAR-190] NullPointerException building

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-war-plugin#364]
**[Trent Nelson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trent)** opened **[MWAR-190](https://issues.apache.org/jira/browse/MWAR-190?redirect=false)** and commented

I don't have much info, except the null pointer exception.

[INFO] Scanning for projects...
[INFO] Reactor build order:
[INFO]   oros
[INFO]   oros rmi component
[INFO]   oros web component
[INFO] Searching repository for plugin with prefix: 'tomcat'.
[INFO] ------------------------------------------------------------------------
[INFO] Building oros
[INFO]    task-segment: [package, tomcat:undeploy, tomcat:deploy]
[INFO] ------------------------------------------------------------------------
[INFO] [site:attach-descriptor]
[INFO] [tomcat:undeploy]
[INFO] Skipping non-war project
[INFO] Preparing tomcat:deploy
[INFO] [site:attach-descriptor]
[INFO] [tomcat:deploy]
[INFO] Skipping non-war project
[INFO] ------------------------------------------------------------------------
[INFO] Building oros rmi component
[INFO]    task-segment: [package, tomcat:undeploy, tomcat:deploy]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources]
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent!
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 5 resources
[INFO] [compiler:compile]
[INFO] Compiling 1 source file to /data/MyDocuments/java/oros/oros-gcap/rmi/target/classes
[INFO] [rmic:rmic {execution: rmi compilation}]
[INFO] Compiling 1 remote classes
[INFO] [resources:testResources]
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /data/MyDocuments/java/oros/oros-gcap/rmi/src/test/resources
[INFO] [compiler:testCompile]
[INFO] Not compiling test sources
[INFO] [surefire:test]
[INFO] Tests are skipped.
[INFO] [jar:jar]
[INFO] Building jar: /data/MyDocuments/java/oros/oros-gcap/rmi/target/oros-rmi.jar
[INFO] [rmic:package {execution: rmi package}]
[INFO] Building RMI stub jar: /data/MyDocuments/java/oros/oros-gcap/rmi/target/oros-rmi-client.jar
[INFO] Building jar: /data/MyDocuments/java/oros/oros-gcap/rmi/target/oros-rmi-client.jar
[INFO] [tomcat:undeploy]
[INFO] Skipping non-war project
[INFO] Preparing tomcat:deploy
[INFO] [resources:resources]
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent!
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 5 resources
[INFO] [compiler:compile]
[INFO] Nothing to compile - all classes are up to date
[INFO] [rmic:rmic {execution: rmi compilation}]
[INFO] No out of date rmi classes to process.
[INFO] [resources:testResources]
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /data/MyDocuments/java/oros/oros-gcap/rmi/src/test/resources
[INFO] [compiler:testCompile]
[INFO] Not compiling test sources
[INFO] [surefire:test]
[INFO] Tests are skipped.
[INFO] [jar:jar]
[INFO] Building jar: /data/MyDocuments/java/oros/oros-gcap/rmi/target/oros-rmi.jar
[INFO] [rmic:package {execution: rmi package}]
[INFO] Building RMI stub jar: /data/MyDocuments/java/oros/oros-gcap/rmi/target/oros-rmi-client.jar
[INFO] Building jar: /data/MyDocuments/java/oros/oros-gcap/rmi/target/oros-rmi-client.jar
[INFO] [tomcat:deploy]
[INFO] Skipping non-war project
[INFO] ------------------------------------------------------------------------
[INFO] Building oros web component
[INFO]    task-segment: [package, tomcat:undeploy, tomcat:deploy]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources]
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent!
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 3 resources
[INFO] Copying 5 resources
[INFO] [compiler:compile]
[INFO] Nothing to compile - all classes are up to date
[INFO] [resources:testResources]
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /data/MyDocuments/java/oros/oros-gcap/web/src/test/resources
[INFO] [compiler:testCompile]
[INFO] Not compiling test sources
[INFO] [surefire:test]
[INFO] Tests are skipped.
[INFO] [war:war]
[INFO] Packaging webapp
[INFO] Assembling webapp[web] in [/data/MyDocuments/java/oros/oros-gcap/web/target/oros]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.plugin.war.util.WebappStructure.getDependencies(WebappStructure.java:109)
at org.apache.maven.plugin.war.util.WebappStructure.analyseDependencies(WebappStructure.java:288)
at org.apache.maven.plugin.war.packaging.DependenciesAnalysisPackagingTask.performPackaging(DependenciesAnalysisPackagingTask.java:46)
at org.apache.maven.plugin.war.AbstractWarMojo.buildWebapp(AbstractWarMojo.java:439)
at org.apache.maven.plugin.war.AbstractWarMojo.buildExplodedWebapp(AbstractWarMojo.java:375)
at org.apache.maven.plugin.war.WarMojo.performPackaging(WarMojo.java:181)
at org.apache.maven.plugin.war.WarMojo.execute(WarMojo.java:143)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:453)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:500)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:479)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:331)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:292)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:301)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16 seconds
[INFO] Finished at: Thu Apr 09 09:56:24 GMT-07:00 2009
[INFO] Final Memory: 30M/61M
[INFO] --------------------------------------------------------------------

---
No further details from [MWAR-190](https://issues.apache.org/jira/browse/MWAR-190?redirect=false)

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Please retry with the latest version. This has been fixed already.

**Comment by jira-importer** [comment]
**[Trent Nelson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trent)** commented

I was using 2.0.10.  Do I have to use 2.1.x?

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Trenton, you might be confusing the Maven version (2.0.10, 2.1.0) with the WAR Plugin version (2.1-beta-1). This issue originates from the plugin, not the Maven core, so you shouldn't need to change your Maven version (though 2.1.0 should be superior compared to 2.0.10) but just update your POM to declare a recent version of the maven-war-plugin.

**Comment by jira-importer** [comment]
**[Trent Nelson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trent)** commented

Thanks Benjamin.  Unfortunately, I don't know how to reproduce it, so at the moment, I can't confirm that it is fixed.  But, I will stay with 2-1.alpha-1 until it happens again, because once it starts happening, as long as I don't do a "clean", it is reproducible.  Then I will upgrade.

Thanks.

**Comment by jira-importer** [comment]
**[Cheng Lee](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cheng.lee)** commented

I'm having the same problem when building from an unrelated project to the one posted. I'm using maven 2.0.10 and WAR plugin 2.1-alpha-2 and could reproduced it. Switching to 2.0.9 fixed the problem.

Maybe I should report a bug on maven itself ;)

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

you should try war 2.1-beta-1. This is has been fixed in the plugin
