### ISSUE TITLE
[MWAR-210] NullPointerException when running war:war

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-war-plugin#390]
**[Willie Wheeler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wwheeler)** opened **[MWAR-210](https://issues.apache.org/jira/browse/MWAR-210?redirect=false)** and commented

This seems to be related to http://jira.codehaus.org/browse/MWAR-170, which is already closed.

[INFO] [war:war]
[INFO] Packaging webapp
[INFO] Assembling webapp[sip07-war] in [C:\Documents and Settings\Willie\workspace\_sip0702\war\target\sip07-war-1.0.0.GA]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.plugin.war.util.WebappStructure.getDependencies(WebappStructure.java:109)
at org.apache.maven.plugin.war.util.WebappStructure.analyseDependencies(WebappStructure.java:288)
at org.apache.maven.plugin.war.packaging.DependenciesAnalysisPackagingTask.performPackaging(DependenciesAnalysisPackagingTask.java:46)
at org.apache.maven.plugin.war.AbstractWarMojo.buildWebapp(AbstractWarMojo.java:439)
at org.apache.maven.plugin.war.AbstractWarMojo.buildExplodedWebapp(AbstractWarMojo.java:375)
at org.apache.maven.plugin.war.WarMojo.performPackaging(WarMojo.java:181)
at org.apache.maven.plugin.war.WarMojo.execute(WarMojo.java:143)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56 seconds
[INFO] Finished at: Sun Aug 02 10:30:03 MST 2009
[INFO] Final Memory: 51M/508M
[INFO] --------------------------------------------------------------------

---
No further details from [MWAR-210](https://issues.apache.org/jira/browse/MWAR-210?redirect=false)

**Comment by jira-importer** [comment]
**[Willie Wheeler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wwheeler)** commented

I found this useful link:

http://www.mail-archive.com/issues@maven.apache.org/msg44538.html

When I ran

mvn -e clean verify

it worked fine.

(In both cases -- i.e. the case where I'm having the error and the case where I'm not -- I'm running mvn verify against the top-level POM of a multi-module project.)

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Have you tried with version 2.1-beta-1 of the WAR Plugin, which includes the fix for MWAR-170?

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Duplicate.
