### ISSUE TITLE
[MWAR-235] The web.xml file included twice into the result war

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-war-plugin#397]
**[Siarhei_Yarkavy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=neon.knight)** opened **[MWAR-235](https://issues.apache.org/jira/browse/MWAR-235?redirect=false)** and commented

Please have a look to the attached demo project and screen-shot

---

**Affects:** 2.1

**Attachments:**
- [asmModule.zip](https://issues.apache.org/jira/secure/attachment/12720502/asmModule.zip) (_1.48 kB_)
- [MWAR-235-test.patch](https://issues.apache.org/jira/secure/attachment/12720478/MWAR-235-test.patch) (_680 bytes_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12720654/pom.xml) (_4.62 kB_)
- [screenshot.jpg](https://issues.apache.org/jira/secure/attachment/12720507/screenshot.jpg) (_24.93 kB_)
- [WarArchiver.java.patch](https://issues.apache.org/jira/secure/attachment/12720572/WarArchiver.java.patch) (_2.55 kB_)

**Issue Links:**
- [MWAR-239](https://issues.apache.org/jira/browse/MWAR-239) web.xml is copied into the war twice
 (_**"is duplicated by"**_)
- [MWAR-242](https://issues.apache.org/jira/browse/MWAR-242) WAR Packaging creates mulitple web.xml's in WEB-INF directory
 (_**"is duplicated by"**_)
- [MWAR-248](https://issues.apache.org/jira/browse/MWAR-248) Plugin warns about missing webxml attribute even if one exists

13 votes, 11 watchers

**Comment by jira-importer** [comment]
**[Siarhei_Yarkavy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=neon.knight)** commented

I have forgotten to mention that is happened only when I specified web.xml location in plugin config
It seems plugin ver 2.1-beta-1 doesn't have this bug.

**Comment by jira-importer** [comment]
**[André Fügenschuh](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fuege)** commented

Confirmed; signing the war generates an error:

```
[INFO] Failed executing 'cmd.exe /X /C "jarsigner.exe -keystore MyKeystore -storepass '*****' -keypass '*****' -storetype JCEKS -sigfile Foo /foo-1.4.0.war Foo"' - exitcode 1
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Failed executing 'cmd.exe /X /C "jarsigner.exe -keystore MyKeystore -storepass '*****' -keypass '*****' -storetype JCEKS -sigfile Foo /foo-1.4.0.war Foo"' - exitcode 1
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed executing 'cmd.exe /X /C "jarsigner.exe -keystore MyKeystore -storepass '*****' -keypass '*****' -storetype JCEKS -sigfile Foo /foo-1.4.0.war Foo"' - exitcode 1
        at org.apache.maven.plugins.jarsigner.AbstractJarsignerMojo.processArchive(AbstractJarsignerMojo.java:495)
        at org.apache.maven.plugins.jarsigner.AbstractJarsignerMojo.processArtifact(AbstractJarsignerMojo.java:372)
        at org.apache.maven.plugins.jarsigner.AbstractJarsignerMojo.execute(AbstractJarsignerMojo.java:197)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        ... 17 more
```

Running the generated signing command (cmd.exe /X /C "jarsigner.exe ...) manually, the error is **similar**:

```
jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: WEB-INF/web.xml
```

on: Windows Vista SP2 x64, JDK 6u21, Maven 2.2.1

**Comment by jira-importer** [comment]
**[Amardeep Sarkar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=asarkar)** commented

Hi, I am facing this same issue. It doesn't matter whether or not I specify the webXml parameter, the generated .war file contains 2 web.xml. I can confirm that war plugin v2.0.2 does not have this bug because it's working for me. Attached is my pom.xml.

**Comment by jira-importer** [comment]
**[Noam Y. Tenne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=noamt)** commented

I can confirm this too. But it happens only in Windows. When built with Linux, it seems to be fine.

**Comment by jira-importer** [comment]
**[Michael Glauche](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mglauche)** commented

Having the same problem, web.xml is getting added twice:

```
[DEBUG] Dump of the current build pathSet content -->
[DEBUG] index.html
[DEBUG] META-INF/MANIFEST.MF
[DEBUG] WEB-INF/faces-config.xml
[DEBUG] WEB-INF/jetty-env.xml
[DEBUG] WEB-INF/web.xml
[DEBUG] -- end of dump --
...
[INFO] Webapp assembled in [921 msecs]
[DEBUG] Excluding [] from the generated webapp archive.
[DEBUG] Including [**] in the generated webapp archive.
[INFO] Building war: C:\work\workspaces\project\project-web\target\project-web-0.2.0-SNAPSHOT.war
[DEBUG] adding directory META-INF/
[DEBUG] adding entry META-INF/MANIFEST.MF
[DEBUG] adding directory images/
[DEBUG] adding directory includes/
[DEBUG] adding directory pages/
[DEBUG] adding directory styles/
[DEBUG] adding directory WEB-INF/
[DEBUG] adding directory WEB-INF/classes/
...
[DEBUG] adding directory WEB-INF/lib/
[DEBUG] adding entry index.html
[DEBUG] adding entry WEB-INF/classes/application.properties
[DEBUG] adding entry WEB-INF/faces-config.xml
[DEBUG] adding entry WEB-INF/jetty-env.xml
[DEBUG] adding entry WEB-INF/lib/aopalliance-1.0.jar
[DEBUG] adding entry WEB-INF/lib/commons-fileupload-1.2.1.jar
... (many more libs)
[DEBUG] adding entry WEB-INF/web.xml
[DEBUG] adding entry WEB-INF/web.xml
[DEBUG] adding directory META-INF/maven/
...
```

Notice the two entries "adding web.xml" ...

Maven is 2.2.1, Maven-War Plugin is set to 2.1 (when unset, 2.1-alpha2 is used and everything works)
Java is 1.6.0_20 on win32.

The zip file does contain the same entry twice, in the same directory.

**Comment by jira-importer** [comment]
**[Michael Glauche](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mglauche)** commented

The problem seems that the WarArchiver is using

addFile( descr, "WEB-INF/web.xml" );

But later the WEB-INF lib does get added, too, so the web.xml is twice in the file-list.

**Comment by jira-importer** [comment]
**[Michael Glauche](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mglauche)** commented

Patch for the WarMojoTest to check duplicate files in a jar. Now the test does (correctly) fail like this:

```
junit.framework.AssertionFailedError: Duplicate Entry in Jar File: WEB-INF/web.xml
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertNull(Assert.java:233)
	at org.apache.maven.plugin.war.WarMojoTest.assertJarContent(WarMojoTest.java:400)
	at org.apache.maven.plugin.war.WarMojoTest.testSimpleWar(WarMojoTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
```

**Comment by jira-importer** [comment]
**[Michael Glauche](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mglauche)** commented

WarArchiver.java.patch does fix this bug in the plexus-archiver war archiver.

First, the overwritten zipFile entry did not get called anymore, now has the same signature as the JarFile method. Second, the webInf warning seems incorrect, as it will be allways thrown. Now it does have a check if the webinf was added from the war plugin before.

**Comment by jira-importer** [comment]
**[Bram](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bram.patelski)** commented

Same problems here, when will the fix be released as a new Maven War plugin?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Michael, thanks for your patches. After applying the test patch, I started to investigate what had gone wrong. Most of your patch for WarArchiver is not needed, it's only the method signature change that is needed, see the linked issue.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Fixed in [r1006261](http://svn.apache.org/viewvc?view=revision&revision=1006261).

Thanks to Michael Glauche for his patches.

A 2.2-SNAPSHOT has been deploy, please test it and report here how it works for you.

**Comment by jira-importer** [comment]
**[Bram](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bram.patelski)** commented

Hi, the last two builds do not have a jar. I'm trying to force my local mvn to just pick the 092327-2.jar but could the 142853-36.jar also be published? Tnx

**Comment by jira-importer** [comment]
**[Bram](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bram.patelski)** commented

Build with 092327-2.jar works fine for me. No more duplicate web.xml in the war.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Dennis, can you have a look to MWAR-248? It sounds like a possible regression due to this change.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Dennis, ping?

**Comment by jira-importer** [comment]
**[Michael Glauche](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mglauche)** commented

`@Stephane`: its more like an old undiscovered bug than a regression, the correct signature was not called, so the check was ignored in the old version. Now we need to see that the check is correct. If i can find some time i'll have a look on it.
