### ISSUE TITLE
[MWAR-243] Error when no artifacts copied to classes directory

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-war-plugin#403]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** opened **[MWAR-243](https://issues.apache.org/jira/browse/MWAR-243?redirect=false)** and commented

When no classes are created or copied to the classes directory the plugin blows up saying the directory does not exist:

[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error installing artifact: File D:\mydir\target\classes does not exist
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error installing artifact: File D:\mydir\target\classes does not exist
at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:143)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
Caused by: org.apache.maven.artifact.installer.ArtifactInstallationException: Error installing artifact: File D:\mydir\target\classes does not exist
at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:119)
at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:105)
... 19 more
Caused by: java.io.IOException: File D:\UserData\Projects\ctis\rapids_rss\rss_applet_war\target\classes does not exist
at hidden.org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:1003)
at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:98)
... 20 more

---

**Affects:** 2.1.1

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12720510/pom.xml) (_781 bytes_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12720591/pom.xml) (_427 bytes_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12720658/pom.xml) (_1.66 kB_)

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

It couldn't be simply it because I have dozens of webapp projects with no classes and they just run fine. You need to attach a sample project to reproduce your setup.

**Comment by jira-importer** [comment]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** commented

Running install with the attached pom.xml in an otherwise empty directory will demonstrate the error.

**Comment by jira-importer** [comment]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** commented

You can see it even with this very simple pom.xml.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Please read the error message. I have tried your pom. It's the same pom as my sample project and the same pom used in ITs

The error message is

Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode)

And
http://maven.apache.org/plugins/maven-war-plugin/war-mojo.html#failOnMissingWebXml

**Comment by jira-importer** [comment]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** commented

This IS a bug. I removed a little too much from the first POM. This one shows it.

**Comment by jira-importer** [comment]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** commented

The second pom attached was incorrect. The third illustrates the issue.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Well, ok. This is what I get with the third pom

```
C:\temp>mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Test War
[INFO]    task-segment: [package]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources {execution: default-resources}]
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\temp\src\main\resources
[INFO] [compiler:compile {execution: default-compile}]
[INFO] No sources to compile
[INFO] [resources:testResources {execution: default-testResources}]
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\temp\src\test\resources
[INFO] [compiler:testCompile {execution: default-testCompile}]
[INFO] No sources to compile
[INFO] [surefire:test {execution: default-test}]
[INFO] No tests to run.
[INFO] [war:war {execution: default-war}]
[INFO] Packaging webapp
[INFO] Assembling webapp[test-war] in [C:\temp\target\test-war-1.0]
[INFO] Processing war project
[INFO] Webapp assembled in[31 msecs]
[INFO] Building war: C:\temp\target\test-war-1.0.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Tue Dec 07 08:34:53 CET 2010
[INFO] Final Memory: 9M/22M
[INFO] ------------------------------------------------------------------------
C:\temp>
```

Add \<version>2.1.1\</version> in your maven-war-plugin definition.
