### ISSUE TITLE
[MWAR-244] Provide a mechanism for not including or having an empty webapp directory

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-war-plugin#414]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** opened **[MWAR-244](https://issues.apache.org/jira/browse/MWAR-244?redirect=false)** and commented

If the configured (or default) webapp directory does not exist, the plugin throws an IllegalArgumentException saying the directory does not exist. There should be a way to proceed without having to create an empty directory.

[INFO] Trace
java.lang.IllegalStateException: basedir D:\mydir\src\main\webapp does not exist
at org.codehaus.plexus.util.DirectoryScanner.scan(DirectoryScanner.java:290)
at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.getFilesToCopy(WarProjectPackagingTask.java:373)
at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.copyResources(WarProjectPackagingTask.java:317)
at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.handleWebResources(WarProjectPackagingTask.java:135)
at org.apache.maven.plugin.war.packaging.WarProjectPackagingTask.performPackaging(WarProjectPackagingTask.java:91)
at org.apache.maven.plugin.war.AbstractWarMojo.buildWebapp(AbstractWarMojo.java:472)
at org.apache.maven.plugin.war.AbstractWarMojo.buildExplodedWebapp(AbstractWarMojo.java:404)
at org.apache.maven.plugin.war.WarMojo.performPackaging(WarMojo.java:197)
at org.apache.maven.plugin.war.WarMojo.execute(WarMojo.java:159)
...

---

**Affects:** 2.1.1

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Again, that sounds weird. It shouldn't be doing that except if you add webResources yourself (which you shouldn't have to do for a default use case). I just tried with a sample project with no webapp directory and it worked.

You are probably using a configuration item wrongly. Please attach a sample project.

**Comment by jira-importer** [comment]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** commented

This is occurring because a webResources block is set up in a company-wide parent pom. The block points to a directory that doesn't exist in my implementation. There seems to be no way to override or remove this configuration inherited from a parent pom.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

blame the parent pom then. You are explicitly asking the plugin to copy some resources. Taking it to other way around, folks would complain that the plugin does not report that a directory does not exist while it was specified.

You can override the definition using an empty webResources element maybe. All in all, the definition in the corporate pom seems fishy to me. Maybe you need to fix it there.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

I don't think adding a "empty webResource element remove the crap from a parent pom" brings any value. I agree it might be useful in your case but this has no valid semantic. Just fix your parent pom. After all, if the parent states that some resources must be copied from directory foo (whatever the config is) then it means it's a corporate standard. If not, well the pom is wrong.
