### ISSUE TITLE
[MWAR-254] The deployement of mar files isn't correctly handled (axis2 @ client side + server side)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-war-plugin#418]
**[Paulo Silva](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paulojmsilva)** opened **[MWAR-254](https://issues.apache.org/jira/browse/MWAR-254?redirect=false)** and commented

Hello!

I did some digging/testing and I found a problem when we have a webapp that uses axis2 at client side + server side.

(...)
Caused by: org.apache.axis2.deployment.DeploymentException: The addressing module is not valid or has not been deployed.
at org.apache.axis2.deployment.ServiceBuilder.processModuleRefs(ServiceBuilder.java:678)
at org.apache.axis2.deployment.ServiceBuilder.populateService(ServiceBuilder.java:327)
... 31 more
Caused by: org.apache.axis2.deployment.DeploymentException: The addressing module is not valid or has not been deployed.
at org.apache.axis2.deployment.ServiceBuilder.processModuleRefs(ServiceBuilder.java:670)
... 32 more

This error will hapen when the addressing module is not found on the expected location(s).

If you deploy the mar files to WEB-INF/modules/ only the server side will work. But if you instead deploy them to WEB-INF/lib/ then both sides will work (client side + server side). I did this test with axis2 v1.5 (we are using webservices with ws-addressing).

To solve this problem I had to patch ArtifactsPackagingTask.java to force the deployement of mar files to WEB-INF/lib/.
I think it would be a good pattern to always deploy artifact dependencies to the lib folder... Maybe there are a few exceptions, but I don't think axis2 mar files are one of them... And IMHO those kind of exceptions should be handled by configuration, when needed.

Another thing I've notice, and don't think this is a problem related to this plugin, is that mar files aren't being included as transitive dependencies :( I had to explicitly declare that dependency on my pom file (I have a direct dependency to another artifact that has a runtime dependency to that mar file, so I think that dependency should be transitively inherited).

Can anyone check this out?

Thanks in advance.

---

**Affects:** 2.1.1

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
